name: Optimize Images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "assets/**"

permissions:
  contents: write

jobs:
  optimize:
    # يمنع إعادة التشغيل بسبب الكوميت اللي بيعمله البوت
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: "75"
          pngQuality: "75"
          webpQuality: "75"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: optimize images"
